baseURL = "https://blog.djangozane.com"
title = "DjangoZane"
locale = "zh-Hans"
enableRobotsTXT = true
enableEmoji = true
theme = "djangozane-clean"
hasCJKLanguage = true
paginate = 10

[menus]
[[menus.main]]
identifier = "home"
name = "首页"
pageRef = "/"
weight = 10

[[menus.main]]
identifier = "post"
name = "文章"
pageRef = "/post"
weight = 20

[[menus.main]]
identifier = "tags"
name = "标签"
pageRef = "/tags"
weight = 30

[[menus.main]]
identifier = "about"
name = "关于"
pageRef = "/about"
weight = 40

[params]
favicon = "/favicon.svg"
backgroundImage = 'img/bg.webp'
[params.search]
enabled = true
[params.photoswipe]
enabled = true
[[params.featuredProjects]]
title = "FlipSwitcher"
description = "Windows窗口切换器"
image = "/img/flipswitcher.webp"
url = "https://github.com/dianbanjiu/FlipSwitcher"
[[params.featuredProjects]]
title = "Djangozane Clean"
description = "简洁美观的hugo主题"
image = "/img/bg.webp"
url = "https://github.com/dianbanjiu/djangozane-clean"

[markup]
[markup.highlight]
codeFences = true
guessSyntax = true
noClasses = false
[markup.goldmark]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true
