baseURL = "https://blog.djangozane.com"
title = "DjangoZane"
languageCode = "zh-Hans"
enableRobotsTXT = true
enableEmoji = true
theme = "djangozane-clean"
hasCJKLanguage = true
paginate = 10

[menus]
[[menus.main]]
identifier = "home"
name = "首页"
pageRef = "/"
weight = 10

[[menus.main]]
identifier = "post"
name = "文章"
pageRef = "/post"
weight = 20

[[menus.main]]
identifier = "tags"
name = "标签"
pageRef = "/tags"
weight = 30

[[menus.main]]
identifier = "about"
name = "关于"
pageRef = "/about"
weight = 40

[params]
favicon = "/favicon.svg"
backgroundImage = 'img/bg.webp'
[params.search]
enabled = true
[params.photoswipe]
enabled = true

[markup]
[markup.highlight]
codeFences = true
guessSyntax = true
noClasses = false
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
